#- id: 0
#  src_node_id: 6
#  dst_node_ids:
#  - 7
#  multicast_id: 10
#  vlan_id: 20
#  pcp: 3
#  size: 1500
#  interval: 1000000
#  max_jitter: 1000000
#  max_latency: 1000000
#- id: 1
#  src_node_id: 6
#  dst_node_ids:
#  - 8
#  multicast_id: 30
#  vlan_id: 10
#  pcp: 4
#  size: 1000
#  interval: 2000000
#  max_jitter: 2000000
#  max_latency: 2000000
#- id: 2
#  src_node_id: 6
#  dst_node_ids:
#  - 7
#  - 8
#  multicast_id: 0
#  vlan_id: 10
#  pcp: 5
#  size: 1000
#  interval: 1000000
#  max_jitter: 1000000
#  max_latency: 1000000
#- id: 3
#  src_node_id: 7
#  dst_node_ids:
#  - 6
#  multicast_id: 11
#  vlan_id: 20
#  pcp: 6
#  size: 400
#  interval: 2000000
#  max_jitter: 2000000
#  max_latency: 2000000
#- id: 4
#  src_node_id: 7
#  dst_node_ids:
#  - 8
#  multicast_id: 31
#  vlan_id: 10
#  pcp: 3
#  size: 1200
#  interval: 1000000
#  max_jitter: 1000000
#  max_latency: 1000000
- id: 5
  src_node_id: 7
  dst_node_ids:
  - 6
  - 8
  multicast_id: 1
  vlan_id: 10
  pcp: 4
  size: 1000
  interval: 1000000
  max_jitter: 1000000
  max_latency: 1000000
- id: 6
  src_node_id: 8
  dst_node_ids:
  - 6
  - 7
  multicast_id: 2
  vlan_id: 10
  pcp: 3
  size: 1000
  interval: 1000000
  max_jitter: 1000000
  max_latency: 1000000
- id: 7
  src_node_id: 8
  dst_node_ids:
  - 6
  - 7
  multicast_id: 3
  vlan_id: 10
  pcp: 4
  size: 1200
  interval: 1000000
  max_jitter: 1000000
  max_latency: 1000000
- id: 8
  src_node_id: 8
  dst_node_ids:
  - 6
  - 7
  multicast_id: 4
  vlan_id: 10
  pcp: 5
  size: 200
  interval: 1000000
  max_jitter: 1000000
  max_latency: 1000000
- id: 9
  src_node_id: 6
  dst_node_ids:
  - 7
  - 8
  multicast_id: 5
  vlan_id: 10
  pcp: 6
  size: 200
  interval: 1000000
  max_jitter: 1000000
  max_latency: 1000000
- id: 10
  src_node_id: 6
  dst_node_ids:
  - 7
  - 8
  multicast_id: 6
  vlan_id: 10
  pcp: 6
  size: 500
  interval: 1000000
  max_jitter: 1000000
  max_latency: 1000000
- id: 10
  src_node_id: 7
  dst_node_ids:
  - 6
  - 8
  multicast_id: 7
  vlan_id: 10
  pcp: 3
  size: 1000
  interval: 1000000
  max_jitter: 1000000
  max_latency: 1000000
- id: 10
  src_node_id: 7
  dst_node_ids:
  - 6
  - 8
  multicast_id: 8
  vlan_id: 10
  pcp: 4
  size: 300
  interval: 1000000
  max_jitter: 1000000
  max_latency: 1000000
- id: 11
  src_node_id: 7
  dst_node_ids:
  - 6
  - 8
  multicast_id: 9
  vlan_id: 10
  pcp: 5
  size: 400
  interval: 1000000
  max_jitter: 1000000
  max_latency: 1000000
- id: 12
  src_node_id: 7
  dst_node_ids:
  - 6
  - 8
  multicast_id: 50
  vlan_id: 10
  pcp: 6
  size: 200
  interval: 1000000
  max_jitter: 1000000
  max_latency: 1000000
- id: 13
  src_node_id: 7
  dst_node_ids:
  - 6
  - 8
  multicast_id: 51
  vlan_id: 10
  pcp: 3
  size: 200
  interval: 1000000
  max_jitter: 1000000
  max_latency: 1000000
- id: 14
  src_node_id: 7
  dst_node_ids:
  - 6
  - 8
  multicast_id: 52
  vlan_id: 10
  pcp: 6
  size: 300
  interval: 1000000
  max_jitter: 1000000
  max_latency: 1000000
- id: 15
  src_node_id: 7
  dst_node_ids:
  - 6
  - 8
  multicast_id: 53
  vlan_id: 10
  pcp: 3
  size: 500
  interval: 1000000
  max_jitter: 1000000
  max_latency: 1000000
- id: 16
  src_node_id: 7
  dst_node_ids:
  - 6
  - 8
  multicast_id: 54
  vlan_id: 10
  pcp: 4
  size: 500
  interval: 1000000
  max_jitter: 1000000
  max_latency: 1000000
- id: 17
  src_node_id: 7
  dst_node_ids:
  - 6
  - 8
  multicast_id: 55
  vlan_id: 10
  pcp: 5
  size: 500
  interval: 1000000
  max_jitter: 1000000
  max_latency: 1000000
- id: 18
  src_node_id: 7
  dst_node_ids:
  - 6
  - 8
  multicast_id: 56
  vlan_id: 10
  pcp: 6
  size: 1000
  interval: 1000000
  max_jitter: 1000000
  max_latency: 1000000
#- id: 19
#  src_node_id: 7
#  dst_node_ids:
#  - 6
#  - 8
#  multicast_id: 57
#  vlan_id: 10
#  pcp: 3
#  size: 1000
#  interval: 1000000
#  max_jitter: 1000000
#  max_latency: 1000000
#- id: 20
#  src_node_id: 7
#  dst_node_ids:
#  - 6
#  - 8
#  multicast_id: 58
#  vlan_id: 10
#  pcp: 4
#  size: 1000
#  interval: 1000000
#  max_jitter: 1000000
#  max_latency: 1000000
#- id: 21
#  src_node_id: 7
#  dst_node_ids:
#  - 6
#  - 8
#  multicast_id: 59
#  vlan_id: 10
#  pcp: 5
#  size: 100
#  interval: 1000000
#  max_jitter: 1000000
#  max_latency: 1000000
#- id: 22
#  src_node_id: 7
#  dst_node_ids:
#  - 6
#  - 8
#  multicast_id: 60
#  vlan_id: 10
#  pcp: 6
#  size: 100
#  interval: 1000000
#  max_jitter: 1000000
#  max_latency: 1000000
#- id: 23
#  src_node_id: 7
#  dst_node_ids:
#  - 6
#  - 8
#  multicast_id: 61
#  vlan_id: 10
#  pcp: 3
#  size: 100
#  interval: 1000000
#  max_jitter: 1000000
#  max_latency: 1000000
#- id: 24
#  src_node_id: 7
#  dst_node_ids:
#  - 6
#  - 8
#  multicast_id: 62
#  vlan_id: 10
#  pcp: 4
#  size: 200
#  interval: 1000000
#  max_jitter: 1000000
#  max_latency: 1000000